name: flowcy_customer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.0.0
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  easy_mask: ^2.0.1
  flutter_holo_date_picker: ^1.0.0-nullsafety.4
  flutter_image_compress: ^1.1.0
  flutter_local_notifications: ^9.1.4
  flutter_native_timezone: ^2.0.0
  flutter_screenutil: ^5.6.0
  flutter_secure_storage: ^7.0.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.0.8
  get: ^4.6.5  
  get_storage: ^2.0.3
  image_picker: ^0.8.4+10
  intl: ^0.18.0
  loading_overlay: ^0.3.0
  loading_animation_widget: ^1.1.0+1
  location: ^4.4.0
  lottie: ^2.1.0
  mask_text_input_formatter: ^2.2.0
  package_info_plus: ^3.0.2
  permission_handler: ^10.2.0
  photo_view: ^0.14.0
  pin_code_fields: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/logo/
    - assets/images/
    - assets/icons/
    - assets/lottie/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700